// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyJgb0IojgS5tE6WJDoCNUrUkftkF348M',
    appId: '1:560606278392:web:d68fc3256a2d684ab0c10d',
    messagingSenderId: '560606278392',
    projectId: 'nodeapp-6b799',
    authDomain: 'nodeapp-6b799.firebaseapp.com',
    storageBucket: 'nodeapp-6b799.appspot.com',
    measurementId: 'G-2FSTLMYSLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBkAe85lf1HmR-4ldWA1n2IN9sLbUmbk',
    appId: '1:560606278392:android:1bcde665552ab5c4b0c10d',
    messagingSenderId: '560606278392',
    projectId: 'nodeapp-6b799',
    storageBucket: 'nodeapp-6b799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrK19qRGwwzl67RLNIMkjceAqVAbndA7o',
    appId: '1:560606278392:ios:b796b9b5bcea932db0c10d',
    messagingSenderId: '560606278392',
    projectId: 'nodeapp-6b799',
    storageBucket: 'nodeapp-6b799.appspot.com',
    iosBundleId: 'com.example.nodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrK19qRGwwzl67RLNIMkjceAqVAbndA7o',
    appId: '1:560606278392:ios:b796b9b5bcea932db0c10d',
    messagingSenderId: '560606278392',
    projectId: 'nodeapp-6b799',
    storageBucket: 'nodeapp-6b799.appspot.com',
    iosBundleId: 'com.example.nodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyJgb0IojgS5tE6WJDoCNUrUkftkF348M',
    appId: '1:560606278392:web:4da8e5c24ad5572eb0c10d',
    messagingSenderId: '560606278392',
    projectId: 'nodeapp-6b799',
    authDomain: 'nodeapp-6b799.firebaseapp.com',
    storageBucket: 'nodeapp-6b799.appspot.com',
    measurementId: 'G-0BE08BXY30',
  );
}
